version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "stakes:1:1,notifications:1:1"
    depends_on:
      - zookeeper
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: app
    volumes:
      - ./mongo_init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
  api:
    build: ./api
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - kafka
    links:
      - kafka
  engine:
    build: ./threshold_engine
    restart: always
    depends_on:
      - kafka
    links:
      - kafka