stakes-controller:
  topicName: "stakes"
  producer:
    bootstrap.servers: "kafka:9092"
notifications-controller:
  timeout: 100
  topics:
    - "notifications"
  consumer:
    bootstrap.servers: "kafka:9092"
    group.id: "notifications-webapp-001"
mongo:
  database: app
  host: mongo
  port: 27017
  username: appuser
  password: appuser
spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: kafka:9092
          auto-add-partitions: true
      bindings:
        input:
          group: notifications
kafka:
  topics: "notifications"
  bootstrap.server: "kafka:9092"
  group.id: "notifications-webapp-002"