stakes-controller:
  topicName: "stakes"
  producer:
    bootstrap.servers: "kafka:9092"
notifications-controller:
  timeout: 100
  topics:
    - "notifications"
  consumer:
    bootstrap.servers: "kafka:9092"
    group.id: "notifications-webapp-001"
mongo:
  database: app
  host: mongo
  port: 27017
  username: appuser
  password: appuser
